const exoplanetsData = [
    {
      planetName: "Planet A",
      day: "5 Earth Days",
      distanceFromHostStar: "2 AU",
      year: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      asteroidHits: "Low",
      atmosphere: "90% Habitable",
      gravity: "1.2 Times the Earth's",
      planetType: "Rocky",
      overallScore: 85,
    },
    {
      planetName: "Planet C",
      day: "8 Earth Days",
      distanceFromHostStar: "1.5 AU",
      year: "15 Earth Years",
      yearOfDiscovery: 2015,
      mass: "3 Earth Mass",
      asteroidHits: "Moderate",
      atmosphere: "70% Habitable",
      gravity: "1.8 Times the Earth's",
      planetType: "Gas Giant",
      overallScore: 90,
    },
    {
      planetName: "Planet D",
      day: "4 Earth Days",
      distanceFromHostStar: "3 AU",
      year: "20 Earth Years",
      yearOfDiscovery: 2018,
      mass: "2.5 Earth Mass",
      asteroidHits: "High",
      atmosphere: "60% Habitable",
      gravity: "2.0 Times the Earth's",
      planetType: "Ice Giant",
      overallScore: 75,
    },
  ];
  const AsteroidsData = [
    {
      planetName: "Planet A",
      day: "5 Earth Days",
      distanceFromHostStar: "2 AU",
      year: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      asteroidHits: "Low",
      atmosphere: "90% Habitable",
      gravity: "1.2 Times the Earth's",
      planetType: "Rocky",
      overallScore: 85,
    },
    {
      planetName: "Planet C",
      day: "8 Earth Days",
      distanceFromHostStar: "1.5 AU",
      year: "15 Earth Years",
      yearOfDiscovery: 2015,
      mass: "3 Earth Mass",
      asteroidHits: "Moderate",
      atmosphere: "70% Habitable",
      gravity: "1.8 Times the Earth's",
      planetType: "Gas Giant",
      overallScore: 90,
    },
    {
      planetName: "Planet D",
      day: "4 Earth Days",
      distanceFromHostStar: "3 AU",
      year: "20 Earth Years",
      yearOfDiscovery: 2018,
      mass: "2.5 Earth Mass",
      asteroidHits: "High",
      atmosphere: "60% Habitable",
      gravity: "2.0 Times the Earth's",
      planetType: "Ice Giant",
      overallScore: 75,
    },
  ];
  const AliensData = [
    {
      planetName: "Planet A",
      day: "5 Earth Days",
      distanceFromHostStar: "2 AU",
      year: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      asteroidHits: "Low",
      atmosphere: "90% Habitable",
      gravity: "1.2 Times the Earth's",
      planetType: "Rocky",
      overallScore: 85,
    },
    {
      planetName: "Planet C",
      day: "8 Earth Days",
      distanceFromHostStar: "1.5 AU",
      year: "15 Earth Years",
      yearOfDiscovery: 2015,
      mass: "3 Earth Mass",
      asteroidHits: "Moderate",
      atmosphere: "70% Habitable",
      gravity: "1.8 Times the Earth's",
      planetType: "Gas Giant",
      overallScore: 90,
    },
    {
      planetName: "Planet D",
      day: "4 Earth Days",
      distanceFromHostStar: "3 AU",
      year: "20 Earth Years",
      yearOfDiscovery: 2018,
      mass: "2.5 Earth Mass",
      asteroidHits: "High",
      atmosphere: "60% Habitable",
      gravity: "2.0 Times the Earth's",
      planetType: "Ice Giant",
      overallScore: 75,
    },
  ];
  const MoonsData = [
    {
      planetName: "Planet A",
      day: "5 Earth Days",
      distanceFromHostStar: "2 AU",
      year: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      asteroidHits: "Low",
      atmosphere: "90% Habitable",
      gravity: "1.2 Times the Earth's",
      planetType: "Rocky",
      overallScore: 85,
    },
    {
      planetName: "Planet C",
      day: "8 Earth Days",
      distanceFromHostStar: "1.5 AU",
      year: "15 Earth Years",
      yearOfDiscovery: 2015,
      mass: "3 Earth Mass",
      asteroidHits: "Moderate",
      atmosphere: "70% Habitable",
      gravity: "1.8 Times the Earth's",
      planetType: "Gas Giant",
      overallScore: 90,
    },
    {
      planetName: "Planet D",
      day: "4 Earth Days",
      distanceFromHostStar: "3 AU",
      year: "20 Earth Years",
      yearOfDiscovery: 2018,
      mass: "2.5 Earth Mass",
      asteroidHits: "High",
      atmosphere: "60% Habitable",
      gravity: "2.0 Times the Earth's",
      planetType: "Ice Giant",
      overallScore: 75,
    },
  ];
  export default exoplanetsData;