const exoplanetsData = [
    {
      planetName: "Planet A",
      day: "5 Earth Days",
      distanceFromHostStar: "2 AU",
      year: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      asteroidHits: "Low",
      atmosphere: "90% Habitable",
      gravity: "1.2 Times the Earth's",
      planetType: "Rocky",
      overallScore: 85,
    },
    {
      planetName: "Planet C",
      day: "8 Earth Days",
      distanceFromHostStar: "1.5 AU",
      year: "15 Earth Years",
      yearOfDiscovery: 2015,
      mass: "3 Earth Mass",
      asteroidHits: "Moderate",
      atmosphere: "70% Habitable",
      gravity: "1.8 Times the Earth's",
      planetType: "Gas Giant",
      overallScore: 90,
    },
    {
      planetName: "Planet D",
      day: "4 Earth Days",
      distanceFromHostStar: "3 AU",
      year: "20 Earth Years",
      yearOfDiscovery: 2018,
      mass: "2.5 Earth Mass",
      asteroidHits: "High",
      atmosphere: "60% Habitable",
      gravity: "2.0 Times the Earth's",
      planetType: "Ice Giant",
      overallScore: 75,
    },
  ];
  const asteroidData = [
    {
      name: "Asteroid A",
      velocity: "1,300 km/h",
      size: "200 tonnes",
      frequency: "5 Earth Years",
      yearOfDiscovery: 2006,
      mass: "2 Earth Mass",
      stability: "Medium",
      waterContent: "20%",
      mineralDeposits: [" Kryptonite ", " Salarcium ", " Irca ", " Ludium ", " Zyntorite "],
      overallImpact: 53,
    },
    {
      name: "Asteroid B",
      velocity: "2,500 km/h",
      size: "300 tonnes",
      frequency: "10 Earth Years",
      yearOfDiscovery: 2010,
      mass: "1.5 Earth Mass",
      stability: "Low",
      waterContent: "15%",
      mineralDeposits: [" Irca ", " Ludium ", " Zyntorite "],
      overallImpact: 62,
    },
    {
      name: "Asteroid C",
      velocity: "900 km/h",
      size: "150 tonnes",
      frequency: "7 Earth Years",
      yearOfDiscovery: 2015,
      mass: "2.5 Earth Mass",
      stability: "High",
      waterContent: "30%",
      mineralDeposits: [" Kryptonite ", " Salarcium "],
      overallImpact: 45,
    }
  ];
  const alienData = [
    {
      name: "Alien Help",
      species: "Insectoid",
      strength: "45%",
      intention: "Bad",
      techLevel: "Medium",
      language: "FLO₣£ŦΩ",
      specialPowers: ["Psychic"],
      weakness: ["Ludium Crystals"],
      overallEffect: -32,
    },
    {
      name: "Alien Omega",
      species: "Reptilian",
      strength: "60%",
      intention: "Neutral",
      techLevel: "Advanced",
      language: "⊗ΣΨ∇",
      specialPowers: ["Invisibility ", " Telekinesis"],
      weakness: ["Cold Temperatures"],
      overallEffect: -20,
    },
    {
      name: "Alien Zoltar",
      species: "Aquatic",
      strength: "30%",
      intention: "Good",
      techLevel: "Low",
      language: "πΩ§Ð",
      specialPowers: ["Water Manipulation ", " Regeneration"],
      weakness: ["Fire"],
      overallEffect: 15,
    },
    
  ];
  const moonData = [
    {
      name: "Lunaris",
      size: "1,500 km",
      gravity: "0.8 G",
      atmosphere: "Thin",
      waterContent: "10%",
      habitable: false,
      orbitalPeriod: "30 Earth Days",
      surfaceComposition: ["Selenium", "Titanium", "Iron"],
      specialProperties: ["Tidal Influence", "Magnetic Anomalies"],
      overallEffect: 25,
    },
    {
      name: "Phobos",
      size: "22.4 km",
      gravity: "0.0057 G",
      atmosphere: "None",
      waterContent: "None",
      habitable: false,
      orbitalPeriod: "7.6 Earth Hours",
      surfaceComposition: ["Phosphorus", "Magnesium"],
      specialProperties: ["Orbital Decay", "Electromagnetic Disruptions"],
      overallEffect: -10,
    },
    {
      name: "Erebus",
      size: "2,300 km",
      gravity: "0.6 G",
      atmosphere: "Dense",
      waterContent: "30%",
      habitable: true,
      orbitalPeriod: "50 Earth Days",
      surfaceComposition: ["Helium-3", "Carbon"],
      specialProperties: ["Thermal Springs", "Geothermal Energy"],
      overallEffect: 50,
    }
  ];
  export { exoplanetsData, asteroidData, alienData, moonData };